language: cpp
compiler:
  - gcc
  - clang
script:
  - mkdir build && cd build && cmake .. && make 2>err && make test && sudo -n make install && sudo -n make uninstall
  - cat err 
  - cat err | wc -l | grep 0 > /dev/null
